

matcha = r"                                                                                                              .,cdxxxc.
                                                                                                            .cONMMMMMWK:
                                                                                                           ;OWMMMMMMMMMNo.
                                                                                                         .xNMMMMMMMMMMMMNc
                                                                                                        ;KMMMMMMMMMMMMMMM0'
                                            .cxOOOdc'                                                  :KMMMMMMMMMMMMMMMMWd.
                                           .dWMMMMMMNOo'                                             .oNMMMMMMMMMMMMMWXNMMX:
                                           ;XMMMMMMMMMMNx,                                          .xNMMMMMMMMMMMMMM0lkWMMx.
                                           lWMMMMMMMMMMMMNkc;'                       .''           ;OWMMMMMMMMMMMMMMM0cl0WMK;
                                          .kMMMMMMMMMMMMMMMMWNOl'        ..        ,o0NNOk0xl::c, cNMMMMMMMMMMMMMMMMMXocOWMWd.
                                          ,KMMMMMMMMMMMMMMMMMMMMNxc,.'''c0KOOdc;,cONMMMMWWMMMMMMXOXMMMMMMMMMMMMMMMMMMKclKNWMK,                        
                                          ;XMMMMMMMMMMMMMMMMMMMMMMWXOOKXWMMMMMMMWWMMMMMMNNWWMMMMMMMMMMMMMMMMMMMMMMMMM0lxNNWMX;                        
                                          ;XMMMMMWWWMMMMMMMMMMMMMMN0OOk0WMMMMMMMMMMMMMMMMNNWMMMMMMMMMMMMMMMMMMMMMMMMMXx0WWWMWl                        
                                          ;XMMMMMN00NMMMMMMMMNOONWXXNWNOxKMMMMMMMMMMMMMWWWWMWWMMMWWMMMMMWWWMMMMMMMMMWo.dWMMMWo                        
                                          ;XMMMMMNXXXNMMMWWW0odKWMWNWMMNddNMMMMMMMMMMMMWWMWWNNMWWWWMMMMMMMMMMMMMMMMM0:lXMMMMWo                        
                                          ;XMMMMMWXKXNMMWNXKo.,OWMWXxd0x.lWMWWMMMMMMMWXXWMWWMMMMMMMMMN0dlc:coxKWMMMMNXWMMMMWWo                        
                                          '0MMMMMMMMMMMMMWWWWK0XMMWO;';. ;0WWWMMMMMMMMWWMMWWMMMMMMNOc'.       .:OWMMMMMMMMMMMX:                       
                                          .OMMMMMMMMMMMMMMNOxdxKWMMMO,.;lOWMMMMMMMMMMMMMMMMMMMMMW0;     ;d.     .xWMMMMWWWWMMM0:                      
                                           oWMMMMMMMMMWXxl;'...':oONWkkNWMMMMMWWWWMMWWWWMMMMMMMMK,      ,Kd      ,KMMMMWWWWMMMMNk,                    
                                           ,KMMMMMMMMKl.    .      ,kNWMMMMMMWXKKNWWWWWWWMMMMMMMXc.     .ll     .cKMMMMMMMMMMMMMMK;                   
                                           .OMMMMMMM0,      ..     ,kNWWMMMMMNXNXXNWMMMMMMMMMMMMWNOc,.......,ldkKWMMMMMMMMMMMMMMMWx.                  
                                          .oNMMMMMMX:      .c.   ,xXWWWWMMMMWXXNWNNWMMMMMWWNXWMMMMMMWK00OkOKNMMMMMMMMMMMMMMMMMMMMMM0:.  .'            
                                         .lXWWWWWWMX;      ;d,.,::xXMWWWMMMMWXXWWWWWMMMMWNKXXWMMMMMMMMMMMMMWWMMMMMWWWMMMMMMMMMMMMMMMNk::Ox.           
                                         .odddl:lOXXO;   .,d0Oddc:xXWMMMMMMMN0KNMMWWWWNKKK0XWMMMMMMMMWWWWMMMWMMMMMMMMMMMWWWWWMMMMMMMMMMMMO;'.         
                                        .;c:'....'c;'...cxKNNXxodod0WMMMMMMMMWNXNNXWWNK0OxxKWMMMMMMMMWWWMMMMMMMMMWWWWWWWWNWWWMMMMMMMMMMMMWXXk.        
                                        ,kKOl..',cdoood0XXNWWXOxxkONWMMMMMMMMMWKKOdKMWWWNOkXWMMMMMMMMMMMMMMMMMMMMWWWWWMMMMMMMMMMMMMMMMMMMNNNo.        
                                       ,kNNOkOKXXNXKNMNXKKXKOkk0NXXNWMMMMMMMMMNKNKoOMMMMMWXNWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWl         
                                      'd0NNNWMMMMMWWWWNXN0xxxXWNXKNWMWMMMMMMMMKOXWNNWMMMMMWWWWWMMMMMMMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMx.        
                                     ;ONXXXXNWMMMWNNNWN0O00KKNNXNNWWMMMMMMMMMMMMMMMMMMMMMMMWWMWWWWMMMMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0'        
                                    cXWWNWMMMMMMWWNNNNNX0OKKKWWWWWNWMMMMMWMMMMMMWNXWMMMMMMMMMMWWWMMMMMMMMMMMMMMMWWWNWMMMMMMMMMMMMMMMMMMMMMMMk.        
                                   :XMMMMMMMMMWXXKKXWMWXK0KXXXNNNWMMMMMMMWWMMMMWOlxXNWMMMMMMMMMMWWWWMMMMMMMMMMMMMWWNNWMMMMMMMMMMMMMMMMMMMMMM0,        
                                  'OMMMMWNNNXNXKXXKKXNNXXK0KXNWWWMMMMMMMMMMMMMNKo.,oxKMMMMMMMMMMWWMMMMMMMMMMMMMMMMMMMMMMMMWMMMMMMMMMMMMMMMMMXc        
                                 :KWWWWNNXNNNX0kkOKXXXKKKXWWNNWMMMMMMMMMMMMMMXko,. ,kNMMMMMMMMMMMMMMMMMMMMMMMMMWWNNWWMMMWWWMMMMMMMMMMMMMMMMMNx.       
                                cKNWWNNNNXX0K0Ok0KK00KXXXXNWNNWMMMMMMMMMMMNKx,..    'dXWMMMMMMMMMMMMMMMMMMMMMMMMWNNNNNWWNNWMWNNMMMMMMMMMMMMMMWx.      
                              .,kWWWNNNXK0kkO00000K000KXNNXNWWWMMMMMMMMWXKOx:.......;kNWMWWMMMMMMMMMMMMMMWNWMMMMMMMMMMWWWNXXXXXWMMMMMMMMMMMMMMMKl.    
                             .xXNNK000OkO00KKKOk0XK000XWMWXXNWMMMMMMMMMWNKkddodOK0O0NWWMMMMMMMMMMMMMMMMMMMWWMMMMMMMMMMMMMMMWWNNNMWWMMMMMMMMMMMMMWKo.  
                          ..:dOKXK0O0KXNNKOkOO0KXNNWWMMMMMMMWWWWWNNWWWWWNWNXKXWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMWNWMMMMMMMMMXl  
                      ..,lxO0O0XNNWMWXXNK0KXNWWWWMMMMMMMMMMMMMMMNXXXNWWWNNWWNWMMMWMMMMMMMMWMMMMMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWMWWNNWWMMXo. 
                  .,:loxk0NWWWWWNX0O00XWMMMMWMMMMMMMMMMMMMMMMMMMMMWWMMMMWWMMWWWNNWWWWWWMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNWWWNNKo
             .,:ldOXNXNWMMMMMNK0OO0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNWNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWX
         .,lkKNWWNWWMMWMMWWNXXXXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMWMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
       .cx0NWMMMMMMWMMWNXNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
         ..'cONWMMWNXXXNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW
              .;cc:,;d0NWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0
                      .cKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMMMMMNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW
                       .:OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNMWWMMMMMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
                     ..',dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMWNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMMMMMMMMMMMMMMMMWX0dl
                 .;lkKXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXk:..  
                ,dxco0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWMMMMMMMMMMMMMMWO'     
              ,ONK;  .oKWMMMMMMMWXXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNWMWWMMMMMMMMMMMMMWKd:;. 
             ,kWMM0c.  .dNMMMMWX0xOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMMMMMMMMMMMMMMMMMWNO
           .oNMMMMMNl....'cOKx:..;kWMMMMMMMMMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
          .oWMMMMMMMXd,''. .,. ;kKXNMMMMMMMMMMMX0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMMMMMMMMMMMMMMMMMMMMMMMM
          ,OMMMMMMMMMNkc,',;:cc:c;lKWMMMMMMMMMMWNWMN0XMMMMMMMMMMMMMMMMMMMMWWNXXXXXO0NMKOXMWK0NWXxll0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
         .:kNMMMMMMMMMMWNXXXKkl,';kNKkKNWMMMMMMMMWKOKNMMWWWMMMMWNNMWKOOOxdlcloood:;okOx::oOo';:'. .kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMMMMMMMMMMMM
           :KMMMMMMMMMMMMMMMMWNNXNMWKxO0dkNMMMMMMN00XK0kOXWMWNKNWN0c..ld;.'cokl;::cc:,,:c;,;,,,'..:KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
          .dWMMMMMMMMMMMMMMMMMMMMMMMMMW0d0WWWMN0KXOoldxd0NMkdloNMW0x:..:..dOOl.'loc,,:c'.,c,''....oWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
           ;0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWK0XWMMMNO:,;ckXMWWWk'. .ckOx..cl;  .o:.'dxo;   :KMMMMMMMMMMMMMMMMMMMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
           ,OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO:..,okONMMMMW0'  .;lxl'',...:xl.,xdc,. ,kWMMMMMMMMMMMMMMMMMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
          ;KWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0:.  .:OXXMMMMMMMO.  ..';lxdlcc;.. 'ol::..oWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
         'OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd.      ;k0WMMMMMMWk..,cc''clc;..,:,;cc:;.:KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
       'oKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXl         cNMWOlOMMMWx. 'dxlc;'',ck0kl,..'oXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
      .kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXc          'xOo..xWMMMWx:''::lx0Okkd:.. ..lXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
l:;;,,:kNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0;           ..',:kXWMMMMWNx..,;;:oOd. ',;,oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0,            ...cox0XXNMMMMWd.'lkx':l..:c;oXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl           ...;;;ccokxOWMMMMNl  lKl';..c:cXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXc'..       .':'.;;lKWWMMMMMMMMNc .c;.lx,;kNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK:',.       .':,.:kXWMMMMMMMMMMMX;   ;xOkxKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWW
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWl          ;;,:;dK00KWMMMMMMMMMM0,  ':xXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO'      ...oolxOXWWNNWMMMMMMMMMMMK; .:0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk.   .;oooOKNWMMMMMMMMMMMMMMMMMMMNkONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMMMMMMMMMMMMMMMMMMMMMMMN0
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk.    ...'oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXl.
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKo'  ....,xNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNWWWMMMMMMMMMMMMMMMMMMXc.. 
MMMMMMMMMMMMMMMMMMMMMMMMMMMMWOddddddx0NMMMM0dddddd0MMO;''',:;:o0W0ddd0WMKddddOWMXxdddddddOWKddddddddd0W0ddd0MMMWKkdoodkXWMMWWWWWMMMMMMMMMMMMMMMXx;
MMMMMMMMMMMMMMMMMMMMMMMMMMMMX;        'kWMN:      :NWl         lWl   ;XWl    ;XMx.       ;Xl         lWl   lWMKc.      .oNMMMWMMWMMMMMMMMMMMMW0:
MMMMMMMMMMMMMMMMMMMMMMMMMMMMX;   :d;   .OM0,  ,'  ,KM0do'   .ld0Wl   ;XWl    ;XMx.  .;lllkN0do'   .ld0Wl   lWWl   .c;.  .xMMMMMMMWMMMMMMMMMMWXc
MMMMMMMMMMMMMMMMMMMMMMMMMMMMX;  .xMK,  .xMk. .xo  .kMMMWl   ;XMMWl   ;XWl    ;XMx.  'OMMMMMMMWl   ;XMMWl   lWX;   dMX;   lWMMMMMMMMMMMMMMMMNx,.
MMMMMMMMMMMMMMMMMMMMMMMMMMMMX;  .xWO.  .xMo  .xd.  dMMMWl   ;XMMWl   .cl'    ;XMx.  .o0O0XMMMWl   ;XMMWl   lWX;  .xMNx:::kWMMMMMMMMMMMMMMWXo.
MMMMMMMMMMMMMMMMMMMMMMMMMMMMX;   .,.   ,0Nc  .Ox.  cWMMWl   ;XMMWl           ;XMx.       oWMMWl   ;XMMWl   lWX;  .xMMMMMMMMMMMMMMMMMMMMWKx,
MMMMMMMMMMMMMMMMMMMMMMMMMMMMX;   ...',l0WK,  '0O.  ;XMMWl   ;XMMWl   .dx,    ;XMx.   ,:::kWMMWl   ;XMMWl   lWX;  .xMWX000XMMMMMMMMMMMWKl.     ..
MMMMMMMMMMMMMMMMMMMMMMMMMMMMX;  .oNNNWMMMO.  'xo.  '0MMWl   ;XMMWl   ;XWl    ;XMx.  'OMMMMMMMWl   ;XMMWl   lWX;  .xMXc  .oWMMMMMMMWKd;.      ..
MMMMMMMMMMMMMMMMMMMMMMMMMMMMX;  .xMMMMMMMd.        .xMMWl   ;XMMWl   ;XWl    ;XMx.  '0MMMMMMMWl   ;XMMWl   lWX;   oWX;   lWMMMMKdlxc        .l'
MMMMMMMMMMMMMMMMMMMWNNWMMMMMX;  .xMMMMMMWl   .::.   oWMWl   ;XMMWl   ;XWl    ;XMx.   ,:::oXMMWl   ;XMMWl   lWNc   .c;.  .dMMMWkl;...     .. ,l.
MMMMMMMMMMMMMMMMMMMWNXNMMMMMX:  .xMMMMMMN:  .xMMd   :NMWl   :XMMWl   :XWl    ;XMx.       'OMMWl   :XMMWl   lWMKl.      'dNMMMK;.:c..  .            ..;
MMMMMMMMMMMMMMMMMMMMMMMMMMMMW0kkkXMMMMMMW0kkOXMMXkkk0WMMKkkk0WMMMKkkk0WMKkkkk0WMXkkkkkkkkONMMMKkkkKWMMMKkkkKMMMMXOxddk0NMMMMMN:  .;l' .      .,cddx0KN
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXO0WMMMMMMKo.   ...      ,d0NWMMMMWM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0o,.'dWWKk0WMk.        .;coONMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXXXkllddl::ll:'. 'oxdl;. .;cc.     .ckXWMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXx;',.            ;0x.              :0WMMMMMMMMMMMMMMMMM"
print